apiVersion: apps/v1
kind: Deployment
metadata:
  name: labgke
  labels: 
    app: pythonappenis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp-denis
  template:
    metadata:
      labels:
        app: pythonapp-denis
    spec:
      containers:
      - name: redis-denis
        image: redis
        ports:
        - name: redis-port
          containerPort: 6379
      - name:  hellopython-denis
        image: gcr.io/alunosturma04/myfirstapp-denis:2.1
        env:
        - name: MESSAGE
          value: "Laboratorio GKE - Denis Braga"
        - name: REDIS_HOST
          value: "localhost"
        ports:
        - name: http-port
          containerPort: 80
